# Jekyll configuration

name: mok 개발일지
description: msc9533

# Url is currently only used only for the RSS feed in feed.xml
url: http://msc9533.github.io
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organization's page leave it empty)
baseurl: ""

author: seung-chan mok
copyright: 2020

share:
  facebook: true
  twitter: true
  gplus: true
  linkedin: true
  pinterest: true
  email: true

social:
  github: msc9533
  stackoverflow: ''
  linkedin:
  instagram: ''
  lastfm: ''
  rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key:

yandex_metrica:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: msc9533
comments: false

permalink: /:year/:month/:title/

# Enable for using pages, more details are here: 
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
remote_theme : streetturtle/jekyll-clean-dark